title: Blast Off Vending
description: A retro vending machine located in Maryland. 
remote_theme: julianolf/jekyll-theme-8bit
logo: nes-pokeball
show_downloads: false
plugins:
 - jekyll-paginate
 - jekyll-seo-tag
paginate: 2
social:
  twitter: https://twitter.com/username
  facebook: https://facebook.com/username
  youtube: https://youtube.com/channel/ID
  instagram: 
  gmail: mailto:edinneny@gmail.com 
